<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function usersCategories($userId)
    {

        $dql = "SELECT category FROM AppBundle:Category category WHERE category.userId = :userId";
        $categories = $this->getEntityManager()->createQuery($dql)->setParameter("userId", $userId)->getResult();
        return $categories;
    }
}
