<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
 public function usersCategory($userId)
 {

     $dql = "SELECT task FROM AppBundle:Task task WHERE task.user = :userId";
     $tasks = $this->getEntityManager()->createQuery($dql)->setParameter("userId", $userId)->getResult();
     return $tasks;
 }
}
